name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  pullreqest:
    name: Check pull request styling
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check branch name and commit messages style
        uses: maximbircu/pull-request-checkstyle@v1.0.0
        with:
          branch-name-regex: '((([a-z])+)+)?(-([a-z])+)+'
          commit-message-title-regex: '^[A-Z].*'
